version: '3.8'

services:
  nginx:
    image: nginx
    container_name: cloud-nginx
    restart: unless-stopped
    depends_on:
      - cloud-ui
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 9000:9000

#  mysql:
#    image: mysql:latest
#    container_name: cloud-mysql
#    restart: unless-stopped
#    ports:
#      - 3306:3306
#    volumes:
#      - mysql-data:/var/lib/mysql
#    env_file:
#      - .env

  cloud-ui:
    image: shiviraj/cloud-ui:latest
    container_name: cloud-ui
    restart: unless-stopped
    ports:
      - 9001:3000

#volumes:
#  mysql-data:

