version: '3.8'

services:
  nginx:
    image: nginx:stable-perl
    container_name: robotutor-tech-nginx
    restart: unless-stopped
    volumes:
      - ./website.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 5000:5000
    networks:
      - cloud-network

  robotutor-tech-ui:
    image: shiviraj/robotutor-tech-ui:latest
    container_name: robotutor-tech-ui
    restart: unless-stopped
    environment:
      PORT: 3000
    networks:
      - cloud-network


networks:
  cloud-network:
    driver: bridge
