version: '3.8'

services:
  service-registry:
    image: shiviraj/service-registry:latest
    container_name: service-registry
    restart: unless-stopped
    environment:
      PORT: 8761
      HOSTNAME: service-registry
    ports:
      - 8761:8761
    networks:
      - cloud-network

networks:
  cloud-network:
    driver: bridge
