version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./jenkins:/var/jenkins_home

  agent:
    image: jenkins/ssh-agent:jdk11
    container_name: agent
    expose:
      - 22
    environment:
      JENKINS_AGENT_SSH_PUBKEY: ${JENKINS_AGENT_SSH_PUBKEY}
