version: '3.8'

services:
  nginx:
    image: nginx:stable-perl
    container_name: robotutor-tech-nginx
    restart: unless-stopped
    volumes:
      - ./website.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 5000:5000
    networks:
      - website

  robotutor-tech-ui:
    image: shiviraj/robotutor-tech-ui:latest
    container_name: robotutor-tech-ui
    restart: unless-stopped
    environment:
      PORT: 3000
    networks:
      - website

  robotutor-tech-backend:
    image: shiviraj/robotutor-tech-backend:latest
    container_name: robotutor-tech-backend
    restart: unless-stopped
    environment:
      PORT: 5001
      MONGODB_URL: ${WEBSITE_MONGODB_URL}
      EMAIL_HOST: ${WEBSITE_EMAIL_HOST}
      EMAIL_PORT: ${WEBSITE_EMAIL_PORT}
      EMAIL: ${WEBSITE_EMAIL}
      PASSWORD: ${WEBSITE_PASSWORD}
    networks:
      - website

networks:
  website:
    driver: bridge
