version: '3.8'
services:

  seed-data:
    image: shiviraj/seed-data:latest
    environment:
      MONGODB_URL: mongodb://mongo:27017
    networks:
      - cloud-network

networks:
  cloud-network:
    driver: bridge
