version: '3.8'

services:
  nginx:
    image: nginx:stable-perl
    container_name: cloud-nginx
    restart: unless-stopped
    depends_on:
      - cloud-ui
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 9000:9000

  mongo:
    image: mongo:4.4.18
    container_name: mongo
    restart: unless-stopped
    ports:
      - 37017:27017
    env_file:
      - .env

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:1.6.15
    restart: always
    volumes:
      - ${MQTT_PATH}/config:/mosquitto/config
      - ${MQTT_PATH}/data:/mosquitto/data
      - ${MQTT_PATH}/log:/mosquitto/log
    ports:
      - 1883:1883

  zookeeper:
    image: bitnami/zookeeper:3.7.2
    container_name: zookeeper
    restart: unless-stopped
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - ./zookeeper/data:/bitnami/zookeeper/data
      - ./zookeeper/logs:/bitnami/zookeeper/logs

  kafka:
    image: bitnami/kafka:3.2.3
    container_name: kafka
    restart: unless-stopped
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - ./kafka/data:/bitnami/kafka/data

#  node-bff:
#    container_name: node-bff
#    image: shiviraj/node-bff:latest
#    restart: unless-stopped
#    depends_on:
#      - mqtt

  cloud-ui:
    image: shiviraj/cloud-ui:latest
    container_name: cloud-ui
    restart: unless-stopped

#volumes:
#  mysql-data:

