version: '3.8'

services:
  nginx:
    image: nginx:stable-perl
    container_name: cloud-nginx
    restart: unless-stopped
    depends_on:
      - cloud-ui
      - cloud-bff
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 9000:9000

  mongo:
    image: mongo:4.4.18
    container_name: mongo
    restart: unless-stopped
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:1.6.15
    restart: always
    volumes:
      - ${MQTT_PATH}/config:/mosquitto/config
      - ${MQTT_PATH}/data:/mosquitto/data
      - ${MQTT_PATH}/log:/mosquitto/log
    ports:
      - 1883:1883

  cloud-ui:
    image: shiviraj/cloud-ui:latest
    container_name: cloud-ui
    restart: unless-stopped
    depends_on:
      - cloud-bff
    environment:
      PORT: 3000

  cloud-bff:
    image: shiviraj/cloud-bff:latest
    container_name: cloud-bff
    restart: unless-stopped
    environment:
      PORT: 3001

#  node-bff:
#    container_name: node-bff
#    image: shiviraj/node-bff:latest
#    restart: unless-stopped
#    depends_on:
#      - mqtt
