version: '3.8'

services:
  cloud-nginx:
    image: nginx:stable-perl
    container_name: cloud-nginx
    restart: unless-stopped
    depends_on:
      - cloud-ui
      - cloud-bff
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 9000:9000
    networks:
      - cloud-network

  backend-mqtt:
    container_name: backend-mqtt
    image: eclipse-mosquitto
    restart: always
    volumes:
      - ./backend-mqtt/config:/mosquitto/config
      - ./backend-mqtt/data:/mosquitto/data
      - ./backend-mqtt/log:/mosquitto/log
    ports:
      - 1884:1884
    networks:
      - cloud-network

  node-mqtt:
    container_name: node-mqtt
    image: eclipse-mosquitto
    restart: always
    volumes:
      - ./node-mqtt/config:/mosquitto/config
      - ./node-mqtt/data:/mosquitto/data
      - ./node-mqtt/log:/mosquitto/log
    ports:
      - 1883:1883
    networks:
      - cloud-network

  mongo:
    image: mongo:4.4.18
    container_name: mongo
    restart: unless-stopped
    ports:
      - 27018:27017
    networks:
      - cloud-network
    volumes:
      - ./mongo-data:/data/db

  cloud-ui:
    image: shiviraj/cloud-ui:latest
    container_name: cloud-ui
    restart: unless-stopped
    depends_on:
      - cloud-bff
    environment:
      PORT: 3000
    networks:
      - cloud-network

  cloud-bff:
    image: shiviraj/cloud-bff:latest
    container_name: cloud-bff
    restart: unless-stopped
    environment:
      PORT: 3001
      API_GATEWAY_BASE_URL: http://cloud-backend-service:4001
    networks:
      - cloud-network

  cloud-backend-service:
    image: shiviraj/cloud-backend-service:latest
    container_name: cloud-backend-service
    restart: unless-stopped
    environment:
      PORT: 4001
      MONGODB_URL: mongodb://mongo:27017
      MQTT_BROKER: tcp://backend-mqtt:1884
      MQTT_USERNAME: ${MQTT_USERNAME}
      MQTT_PASSWORD: ${MQTT_PASSWORD}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL: ${EMAIL}
      PASSWORD: ${PASSWORD}
    networks:
      - cloud-network

networks:
  cloud-network:
    driver: bridge
