version: '3.8'

services:
  nginx:
    image: nginx:stable-perl
    container_name: cloud-nginx
    restart: unless-stopped
    depends_on:
      - cloud-ui
      - cloud-bff
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 9000:9000

  mongo:
    image: mongo:4.4.18
    container_name: mongo
    restart: unless-stopped
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}


  cloud-ui:
    image: shiviraj/cloud-ui:latest
    container_name: cloud-ui
    restart: unless-stopped
    depends_on:
      - cloud-bff
    environment:
      PORT: 3000

  cloud-bff:
    image: shiviraj/cloud-bff:latest
    container_name: cloud-bff
    restart: unless-stopped
    environment:
      PORT: 3001
      API_GATEWAY_BASE_URL: http://api-gateway:4000

  service-registry:
    image: shiviraj/service-registry:latest
    container_name: service-registry
    restart: unless-stopped
    environment:
      PORT: 8761
      HOSTNAME: service-registry
    ports:
      - 8761:8761

  api-gateway:
    image: shiviraj/api-gateway:latest
    container_name: api-gateway
    restart: unless-stopped
    environment:
      PORT: 4000
      AUTH_SERVICE_BASE_URL: http://auth-service:9001
    depends_on:
      - auth-service

  auth-service:
    image: shiviraj/auth-service:latest
    container_name: auth-service
    restart: unless-stopped
    environment:
      PORT: 9001
      MONGODB_URL: ${MONGODB_URL}
      SERVICE_REGISTRY_URL: http://service-registry:8761
    depends_on:
      - service-registry

#  node-bff:
#    container_name: node-bff
#    image: shiviraj/node-bff:latest
#    restart: unless-stopped
#    depends_on:
#      - cloud-bff
#    environment:
#      PORT: 3002
